project:
  type: book

book:
  title: "esqLABS R Coding Practice"
  reader-mode: true

  page-footer:
    left: |
      This book is a work in progress.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.

  site-url: https://esqlabs.github.io/esqlabs-r-coding-standards/
  repo-url: https://github.com/esqLABS/esqlabs-r-coding-standards
  repo-branch: main
  repo-actions: [edit, issue]

  chapters:
    - index.qmd
    - style.qmd
    - tidyverse_style.qmd
    - good_practices.qmd
    - caveats.qmd
    - resources.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - esqlabs.scss
    code-link: true

    author-meta: "Felix MIL, Tanya Zasedateleva"
    callout-appearance: simple

editor: visual



