# esqLABS' R Style Guide

At esqlabs, we follow the [tidyverse style guide](https://style.tidyverse.org) with very few changes. The following sections will outline the most important differences wit the Tidyverse guide and why these difference exists.

## Syntax

### Naming Conventions

In order to better match the naming conventions used on other software projects within the company, the way names are defined is different from the tidyverse style guide.

The naming style depends on the type of object: 

-   Variable and function names should use only letters and numbers. Use `camelCase` to separate words within a name. 

    ``` r
    # Good

    fitModel <- function(){}

    resultsDf <- data.frame()

    # Bad

    fit_model <- function(){}

    ResultsDf <- data.frame()
    ```

-   Class names should use `PascalCasing`.

-   True constant variables should use `ALL_CAPS` casing. 

    ``` r
    # Good
    CONSTANT_VAR <- 1

    # Bad

    constant_var <- 1
    constantVar <- 1
    ```

-   Use meaningful and understandable names. The code should read as a story and only some well-known abbreviations (such as pk) should be used.

    ``` r
    # Good

    # Primary key
    pk <- 1

    # Bad

    # Primary key
    primary_key <- 1
    ```

### Spacing

Because it is not explicitly said in the tidyverse guideline and for improved code readability, use the following indentation settings:

-   Use indentation of 2, 

-   Use spaces instead of tabs.

## Functions

### `return()`

Prefer using `return()` for explicitly returning result, although you can rely on R to implicitly return the result of the last evaluated expression in a function. 
